---
# https://github.com/compose-spec/compose-spec/blob/master/spec.md
# TODO: Once production is ready, create a separate docker-compose.debug.yml for debugging.

version: "3"
services:
  app:
    container_name: fybot_container
    image: fybot
    build:
      context: .
      target: development
      # target: production
    hostname: fybot
    restart: always
    ports:
      - "8501:8501"
      - "5678:5678"
    volumes:
      # - ./fybot:/usr/src/fybot
      - type: volume
        source: ./fybot
        target: /usr/src/fybot
      - type: bind
        source: /home/.secrets
        target: /usr/src/.secrets
    networks:
      - fybot-net
      - db-net
    depends_on:
      - db-server

  db-server:
    container_name: db-server
    image: postgres:13
    hostname: ${DB_HOST}
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./fybot/config/create_tables_docker.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-net

  db-admin:
    container_name: db-admin
    image: adminer
    hostname: db-admin
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - db-server
    networks:
      - fybot-net
      - db-net

volumes:
  db-data:

networks:
  fybot-net:
  db-net:
