---
# https://github.com/compose-spec/compose-spec/blob/master/spec.md

version: "3"
services:
  db-server:
    container_name: db-server
    image: postgres:13
    hostname: db.server
    restart: always
    # specify the local path to the .env file
    # or comment out and use the command below during docker compose
    # docker compose --env-file /PATH/file.env up
    env_file:
      - /Users/ramirezae/fybot.env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./fybot/config/create_tables.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - db-net

  db-admin:
    container_name: db-admin
    image: adminer
    hostname: db-admin
    restart: unless-stopped
    environment:
      - ADMINER_DEFAULT_SERVER=localhost
      - ADMINER_DESIGN=pepa-linha
    ports:
      - "8080:8080"
    depends_on:
      - db-server
    networks:
      - fybot-net
      - db-net

  app:
    container_name: fybot
    build: .
    image: local/fybot:beta
    hostname: fybot
    restart: unless-stopped
    ports:
      - "8501:8501"
    # the container needs access to the TDA token so this is mounted as volume
    # map the location of the TDA token to a location accesible by the container.
    # you only need to replace /Users/ramirezae/.tda/td_access_token.pickle
    volumes:
      - ./fybot:/usr/src/fybot
      - /Users/ramirezae/.tda/td_access_token.pickle:/usr/src/fybot/config/td_access_token.pickle
    # specify the local path to the .env file
    # or comment out and use the command below during docker compose
    # docker compose --env-file /PATH/file.env up
    env_file:
      - /Users/ramirezae/fybot.env
    networks:
      - fybot-net
      - db-net
    depends_on:
      - db-server
      - db-admin

volumes:
  db-data:


networks:
  fybot-net:
  db-net:
